// Component Name : RootLayout

import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Toaster } from "@/components/ui/toaster"
import NavigationBar from "@/components/NavigationBar"
import { validateRequest } from "../lib/lucia"
import { signOut } from "../lib/actions/auth.actions";

// section 1 
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const { user } = await validateRequest();
  return (
    // section 2 
    <html lang="en">
      <body className={inter.className}>
      <NavigationBar user={user} signOut={signOut}/>
        {children}
        <Toaster />
      </body>
    </html>
  )
}



/**
 * ---------------------------------------------------------------------
 * File Name      : layout.tsx
 * Component Name : RootLayout
 * Component Type : Next Layout
 * Date Created   : 2024-06-24
 * Dev Initials   : Elias Emon
 * ------------------------------
 * Question: Why was it necessary to create this component?
 * Answer  : This component was necessary to establish a consistent layout and global structure for the Next.js application, including setting up a navigation bar, user authentication, and global styles. 
 *
 * ------------------------------
 * Question: What does this component do?:
 * Answer  : This component sets up the root layout for the application. It fetches the authenticated user's information, renders the navigation bar with user details and sign-out functionality, and includes a toaster for notifications. It also applies global styles and fonts.
 * ------------------------------
 * Section Comments:   (Enter "none" if you have no comments)
 * Section 1:
 * Initializes the Inter font and metadata for the application.
 *
 * Section 2:
 * Defines and renders the root layout, including the navigation bar, children components, and toaster for notifications.
 *
 *
 * ------------------------------
 * Input Comments:     (Enter "none" if you have no comments)
 * None
 * ------------------------------
 * Output Comments:    (Enter "none" if you have no comments)
 * None
 * ------------------------------
 * Additional Comments:
 * Question: Did you have to write any unusual code?
 * Answer  : NO.
 *
 */